### ISSUE TITLE
map_coverage_p_low.f

### ISSUE THREAD

**Issue by Melcore79** [StereoPhotoClinometry/archivingTools#12]
Output isn't always in columns as it should be. This causes problems, especially when uploading to OALF. I think the problem is 1) When the numbers get large there is no column separator and 2) When there is no image over that pixel the output becomes ******.

See a screenshot of the best res output.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/66811160/152431680-b9ac6871-106e-4695-aa94-4e10cba8953a.png">

**Comment by ericepalmer** [comment]
What is this the output product of?  Clearly, the variables got too big (more than 99) so it ran over the spacing provided.  It seems like that must be a bug, so we need to look at why where are getting it (maybe division by nearly zero).

Which line is it?  What do the other files show on that line for their output?

**Comment by Melcore79** [comment]
I'm trying to get you set up in Dropbox... give me a bit.

**Comment by Melcore79** [comment]
Well I was working with an old file, and now I can't reproduce the problem. Apparently the data set I have is not what I thought I had. Scratch for now. I may open this back up again someday when we can actually poke at it.

**Comment by Melcore79** [comment]
I can say that some pixels from coverage had "0" for coverage, so that is probably what is going on, division by zero. Here's screen shot of that line number for coverage and resolution.
<img width="906" alt="image" src="https://user-images.githubusercontent.com/66811160/152437548-e37d9a77-eec3-4902-8610-39be7d154150.png">
<img width="906" alt="image" src="https://user-images.githubusercontent.com/66811160/152437622-7684ba34-b136-48d0-b1b7-a85d193ab5c9.png">

**Comment by Melcore79** [comment]
I'm thinking the data I had was from an older version. I figured out how to reproduce a similar situation, and it behaves as we intend it to.
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/66811160/152439332-74293160-7da5-4638-ac69-2dd9479b7108.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/66811160/152439366-f61245f5-9cdc-48fc-beb6-5176a356f84b.png">
