### ISSUE TITLE
pgm2ascii.c

### ISSUE THREAD

**Issue by ericepalmer** [StereoPhotoClinometry/archivingTools#2]
Where should we put the request to scale.

I thought it would be good for a command line argument, but now I waffling on it.  

pgm2ascii <filename> <number>
or
pgm2ascii <filename> -n <number>

Almost always we're going to want some scaling, so now I am thinking it might be good to have as a prompt.

pgm2ascii <filename>
What scaling do you want?

**Comment by Melcore79** [comment]
I think we'll eventually want to use this program in a script. I like to avoid making a bunch of {echo "variable" >> tmpJRW"} to then feed into a program. How about we made it a mandatory command line argument? If we don't want to change the values, then we just enter in a scaling of 1.

So if we are using it on sigmas.pgm, we get the scaling from sigmas.txt for something like this:
{ pgm2ascii .013 sigmas.pgm}

And if we're using it on coverage_p.pgm:
{pgm2ascii 1 coverage_p.pgm}

Or is there some standard where filenames should always come first followed by other variables? Might make more sense actually to have the filename first regardless... I don't know.

**Comment by ericepalmer** [comment]
﻿I’d suggest echo <value> | pgm2sacii file

Mistyped by my phone



Mistyped by my phone

**Comment by ericepalmer** [comment]
What is the status of this?  Still need to do?

**Comment by Melcore79** [comment]
I will close this. With our current pipeline I'm not sure how much we'll be using pgm2ascii, and since it's already working well enough I don't see a need to change it.
