### ISSUE TITLE
globalStat update

### ISSUE THREAD

**Issue by Melcore79** [StereoPhotoClinometry/archivingTools#27]
Per our email conversation on 15 Aug 2023, I am requesting globalStat to be updated to output maplet coverage data in addition to image coverage data. The routines from COVERAGE can be used, but the output should be 360 sample by 181 lines, like the rest of the output from globalStat. I am attaching an image showing the current pipeline. Note that the arrow pointing to the Sigma cube can be accomplished by using different inputs to GMT and does not require a software update. The arrow pointing to Best Maplet is the modification I am requesting, by incorporating it into globalStat. Let me know if you have any further questions.

IMPORTANT: The current version of globalStat is in the branch globalStat-output-meters and is v2.4. I think it would be good to merge it into the main branch before modifying the code.

Please charge to account 1794 (PDART).

<img width="983" alt="image" src="https://github.com/StereoPhotoClinometry/archivingTools/assets/66811160/097287a7-a293-40b9-9674-2d57c3c3d8e2">

**Comment by Melcore79** [comment]
I just realized that to make the best map product using the current pipeline, I run COVERAGE multiple times, one for each maplet resolution. I think the best solution is to have globalStat ask if you'd like maplet coverage or image coverage, and if maplet coverage then it asks for a resolution. However, I'll trust your judgment if you think of a better way.

**Comment by Melcore79** [comment]
Wow, don't mis-click when you are trying to click the <down arrow> next to "Close with comment" because it instantly closes the issue.

**Comment by ericepalmer** [comment]
I've merged v2.4 (meters) for you.

If I understand what you want, global stat is not well suited for maplets -- it is image based.  Thus, I should update COVERAGE

**Comment by ericepalmer** [comment]
So, what output format do you want this to be?

Just to confirm, this tool should pull every maplet and project every pixel onto the surface and report out the 181x360 bins, right?  Actually, for this one, it can be 180x360 (it area).  What do you want???
