### ISSUE TITLE
Moving central vector of a bigmap.

### ISSUE THREAD

**Issue by Melcore79** [StereoPhotoClinometry/archivingTools#38]
We need a program to move the central vector of a bigmap because that comes in useful quite often.

Currently, I'm having trouble making a geoTiff at a polar region. I use GDAL's ogr2ogr to transform the projection from the backplanesGMT (i.e. lat, lon, radius vectors) to polar stereographic, then gdal_grid, but it keeps changing the lat by ~0.5 deg. We could shift the central vector by the arbitrary amount needed so GDAL will place the topography in the right location.

There are many other times where this program will be useful, as opposed to using SHIFT to shift an entire directory, which is slow and uses lots of hard drive space.

**Comment by ericepalmer** [comment]
Code created to shift it.
Please test

**Comment by Melcore79** [comment]
The code will currently overwrite a MAP if the output name is a longer version of the original name. For example, if the MAP file is P00066 and you make the output name be P00066-shift, it will truncate the name to six characters (i.e. P00066) and overwrite the file. Shortening to 6 characters isn't a big deal, but overwriting data is.

Might be good to put in some checks, or output more information so the user will know what they can and cannot do.
