### ISSUE TITLE
map_coverage_p_low pulling pixels that are in shadow

### ISSUE THREAD

**Issue by Melcore79** [StereoPhotoClinometry/archivingTools#50]
map_coverage_p_low is indicating there are high resolution images over a bigmap when in fact those images have the topography in shadow and the best resolution images with illuminated topography have a resolution 2 times worse (I didn't copy over the fully illuminated topography images, only the ones with lots of shadow). If we had map_coverage_p_low check the T1 value in the SUMFILE (instead of just reporting it) I think this would solve the problem. Could you please update the code when possible? More details below.

To give you data to work with, I made a directory in playground called MercuryTestmap_coverage_p_low. This directory is bare bones but enough to run map_coverage_p_low. For example, there are no landmark files.

I currently have coverage_p.in containing N0220850474M, N0220850481M, and N0220850488M.
The input/output from map_coverage_p_low looks like this...
{{{
(isis) <Egwene> MercuryTestmap_coverage_p_low$ ~/bin/map_coverage_p_low 
 Version:    1.20000005    
 Input RESLIM (km/px)
1
 Input MAPNAME
AGW151
 Use all images? (y/n)
n
        PICNM              Angle      Res?           # LMK   Min Thres    Max Thres     Pixel       Used
 N0220850474M    29.755     0.022       200         282              4095             79582     79582
 N0220850481M    28.943     0.022        82          292              4095             151371    140195
 N0220850488M    29.585     0.023        78          284             4095              153160    139882
}}}

I've also copied cube files of 2 of the images showing the MOSAIC output of those images with the bigmap. These cubes are in the working directory (i.e. MercuryTestmap_coverage_p_low)

Assuming I've pasted the picture correctly, you can see below the best image res (AGW151-res.cub), number of images (AGW151-cov.cub), and the 2 MOSAIC outputs(N0220850481M-AGW151.cub and N0220850488M-AGW151.cub), showing that areas in shadow are being shown as valid pixels. Remember that for best image resolution the NoDATA is set to be 9999 m/px and thus appears white, while the ~0.019 m/px values that are "valid" are appearing as black.

<img width="2164" alt="image" src="https://github.com/user-attachments/assets/80996d5e-97a2-4820-be01-9146e8a273e6">

**Comment by Melcore79** [comment]
Bumping this to keep it on your radar. If you can get it finished before the end of next week that would be great.

**Comment by Melcore79** [comment]
The updated version of map_coverage_p_low looks to be working correctly. Here is the updated output. You can see that now the shadows part of the image is appearing as white (i.e. NoData) in the res and cov cubes.

Eric, once you have initiated the merge you should close this issue.


<img width="2158" alt="Untitled" src="https://github.com/user-attachments/assets/b42523f3-aaf8-42f8-9668-9c586060fa1e">

**Comment by Melcore79** [comment]
After I posted the above I ran the program with a different max res, and was surprised by the results.

To make testing simpler, I narrowed it down to image N0215894570M, which is in the playground directory. I provide a visual, but you can see the difference in the output to the terminal

{{{
<Egwene> MercuryTestmap_coverage_p_low$ ~/bin/t.map_coverage_p_low 
 Version:    1.29999995    
 Input RESLIM (km/px)
.25
 Input MAPNAME
AGW151
 Max pixels:        707281
 Use all images? (y/n)
n
 In file:  coverage_p.in                                                           
        PICNM     Angle      Res?     # LMK Min_Thres Max_Thres   T_Pixel Val_Pixel   Updated  Ex_T1/T2
 N0215894570M    46.270     0.042       317       265      4095    447834    447024    447024         0
}}}

{{{
<Egwene> MercuryTestmap_coverage_p_low$ ~/bin/t.map_coverage_p_low 
 Version:    1.29999995    
 Input RESLIM (km/px)
.06
 Input MAPNAME
AGW151
 Max pixels:        707281
 Use all images? (y/n)
n
 In file:  coverage_p.in                                                           
        PICNM     Angle      Res?     # LMK Min_Thres Max_Thres   T_Pixel Val_Pixel   Updated  Ex_T1/T2
 N0215894570M    46.078     0.042       317       265      4095    447834    442408    442408         0
}}}

Notice that "Val_Pixel" is different between the two, even though the only thing that changed is the RESLIM.

Not sure if the following helps or adds to the confusion, but when I the program in the main directory I get a different output then when I run it in the playground directory, even though I'm using the same image and RESLIM.

Here it is in my main directory

{{{
<Egwene> AgwoFaculaNoCutOff$ ~/bin/t.map_coverage_p_low 
 Version:    1.29999995    
 Input RESLIM (km/px)
.06
 Input MAPNAME
TEMP01
 Max pixels:        707281
 Use all images? (y/n)
n
 In file:  coverage_p.in                                                           
        PICNM     Angle      Res?     # LMK Min_Thres Max_Thres   T_Pixel Val_Pixel   Updated  Ex_T1/T2
 N0215894570M    45.969     0.042       865       265      4095    447892    440284    440284         0
}}}

I did not provide visuals since I think it is evident from the terminal output, but let me know if you want visuals.

**Comment by Melcore79** [comment]
I may have a clue as to why the two directories give different outputs. It looks like I ran GEOMETRY/AUTOREGISTER since I made the the playground directory. I'm still surprised moving the S/C modifies ~2000 pixels, but I can see how that would changes slopes and the like.

Here's "sdiff" on the two SUMFILES in image form since I think formatting will mess up a simple copy/paste.

![Untitled](https://github.com/user-attachments/assets/673dbcfa-9074-4745-8562-c31b5f23c35f)

**Comment by Melcore79** [comment]
Here's a list of all the images that passed the 60 m RESLIM. The left shows the 60 m RESLIM, the right the 250 m RESLIM. In the very last column I have a ratio of the Val_Pixel @ 250 m / Val_Pixel @ 60 m. I would expect all the ratios to have a value of 1, but over half of them do not. In all cases the RESLIM 60 m gives fewer valid pixels than the 250 RESLIM.

 
![Untitled 2](https://github.com/user-attachments/assets/72ad05d1-43a0-4f3a-aa05-25208546e1c5)

**Comment by ericepalmer** [comment]
done

**Comment by ericepalmer** [comment]
Val_pixels will change if there are pixels that change from above the threshold to below the threshold.
I'm not sure there is a problem.  Was there something else?

**Comment by Melcore79** [comment]
program looks to be in good shape. Go ahead and initiate a pull request.
